/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as PlayYourTurnRouteImport } from './routes/play.your-turn'
import { Route as PlayWaitingRouteImport } from './routes/play.waiting'
import { Route as PlayThemedRouteImport } from './routes/play.themed'
import { Route as PlayRandomRouteImport } from './routes/play.random'
import { Route as PlayQuickRouteImport } from './routes/play.quick'
import { Route as PlayMatchSelectRouteImport } from './routes/play.match-select'
import { Route as PlayDirectWordRouteImport } from './routes/play.direct-word'
import { Route as PlayChallengeSentRouteImport } from './routes/play.challenge-sent'
import { Route as MatchResultRouteImport } from './routes/match.result'
import { Route as PlayThemedThemeRouteImport } from './routes/play.themed.$theme'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)
const PlayYourTurnRoute = PlayYourTurnRouteImport.update({
  id: '/your-turn',
  path: '/your-turn',
  getParentRoute: () => PlayRoute,
} as any)
const PlayWaitingRoute = PlayWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => PlayRoute,
} as any)
const PlayThemedRoute = PlayThemedRouteImport.update({
  id: '/themed',
  path: '/themed',
  getParentRoute: () => PlayRoute,
} as any)
const PlayRandomRoute = PlayRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => PlayRoute,
} as any)
const PlayQuickRoute = PlayQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => PlayRoute,
} as any)
const PlayMatchSelectRoute = PlayMatchSelectRouteImport.update({
  id: '/match-select',
  path: '/match-select',
  getParentRoute: () => PlayRoute,
} as any)
const PlayDirectWordRoute = PlayDirectWordRouteImport.update({
  id: '/direct-word',
  path: '/direct-word',
  getParentRoute: () => PlayRoute,
} as any)
const PlayChallengeSentRoute = PlayChallengeSentRouteImport.update({
  id: '/challenge-sent',
  path: '/challenge-sent',
  getParentRoute: () => PlayRoute,
} as any)
const MatchResultRoute = MatchResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => MatchRoute,
} as any)
const PlayThemedThemeRoute = PlayThemedThemeRouteImport.update({
  id: '/$theme',
  path: '/$theme',
  getParentRoute: () => PlayThemedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/match/result': typeof MatchResultRoute
  '/play/challenge-sent': typeof PlayChallengeSentRoute
  '/play/direct-word': typeof PlayDirectWordRoute
  '/play/match-select': typeof PlayMatchSelectRoute
  '/play/quick': typeof PlayQuickRoute
  '/play/random': typeof PlayRandomRoute
  '/play/themed': typeof PlayThemedRouteWithChildren
  '/play/waiting': typeof PlayWaitingRoute
  '/play/your-turn': typeof PlayYourTurnRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/play/': typeof PlayIndexRoute
  '/play/themed/$theme': typeof PlayThemedThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/match/result': typeof MatchResultRoute
  '/play/challenge-sent': typeof PlayChallengeSentRoute
  '/play/direct-word': typeof PlayDirectWordRoute
  '/play/match-select': typeof PlayMatchSelectRoute
  '/play/quick': typeof PlayQuickRoute
  '/play/random': typeof PlayRandomRoute
  '/play/themed': typeof PlayThemedRouteWithChildren
  '/play/waiting': typeof PlayWaitingRoute
  '/play/your-turn': typeof PlayYourTurnRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/play': typeof PlayIndexRoute
  '/play/themed/$theme': typeof PlayThemedThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/match/result': typeof MatchResultRoute
  '/play/challenge-sent': typeof PlayChallengeSentRoute
  '/play/direct-word': typeof PlayDirectWordRoute
  '/play/match-select': typeof PlayMatchSelectRoute
  '/play/quick': typeof PlayQuickRoute
  '/play/random': typeof PlayRandomRoute
  '/play/themed': typeof PlayThemedRouteWithChildren
  '/play/waiting': typeof PlayWaitingRoute
  '/play/your-turn': typeof PlayYourTurnRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/play/': typeof PlayIndexRoute
  '/play/themed/$theme': typeof PlayThemedThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/match'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/rooms'
    | '/rules'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/match/result'
    | '/play/challenge-sent'
    | '/play/direct-word'
    | '/play/match-select'
    | '/play/quick'
    | '/play/random'
    | '/play/themed'
    | '/play/waiting'
    | '/play/your-turn'
    | '/rooms/$roomId'
    | '/play/'
    | '/play/themed/$theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/match'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/rooms'
    | '/rules'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/match/result'
    | '/play/challenge-sent'
    | '/play/direct-word'
    | '/play/match-select'
    | '/play/quick'
    | '/play/random'
    | '/play/themed'
    | '/play/waiting'
    | '/play/your-turn'
    | '/rooms/$roomId'
    | '/play'
    | '/play/themed/$theme'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/match'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/rooms'
    | '/rules'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/match/result'
    | '/play/challenge-sent'
    | '/play/direct-word'
    | '/play/match-select'
    | '/play/quick'
    | '/play/random'
    | '/play/themed'
    | '/play/waiting'
    | '/play/your-turn'
    | '/rooms/$roomId'
    | '/play/'
    | '/play/themed/$theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/play/your-turn': {
      id: '/play/your-turn'
      path: '/your-turn'
      fullPath: '/play/your-turn'
      preLoaderRoute: typeof PlayYourTurnRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/waiting': {
      id: '/play/waiting'
      path: '/waiting'
      fullPath: '/play/waiting'
      preLoaderRoute: typeof PlayWaitingRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/themed': {
      id: '/play/themed'
      path: '/themed'
      fullPath: '/play/themed'
      preLoaderRoute: typeof PlayThemedRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/random': {
      id: '/play/random'
      path: '/random'
      fullPath: '/play/random'
      preLoaderRoute: typeof PlayRandomRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/quick': {
      id: '/play/quick'
      path: '/quick'
      fullPath: '/play/quick'
      preLoaderRoute: typeof PlayQuickRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/match-select': {
      id: '/play/match-select'
      path: '/match-select'
      fullPath: '/play/match-select'
      preLoaderRoute: typeof PlayMatchSelectRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/direct-word': {
      id: '/play/direct-word'
      path: '/direct-word'
      fullPath: '/play/direct-word'
      preLoaderRoute: typeof PlayDirectWordRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/challenge-sent': {
      id: '/play/challenge-sent'
      path: '/challenge-sent'
      fullPath: '/play/challenge-sent'
      preLoaderRoute: typeof PlayChallengeSentRouteImport
      parentRoute: typeof PlayRoute
    }
    '/match/result': {
      id: '/match/result'
      path: '/result'
      fullPath: '/match/result'
      preLoaderRoute: typeof MatchResultRouteImport
      parentRoute: typeof MatchRoute
    }
    '/play/themed/$theme': {
      id: '/play/themed/$theme'
      path: '/$theme'
      fullPath: '/play/themed/$theme'
      preLoaderRoute: typeof PlayThemedThemeRouteImport
      parentRoute: typeof PlayThemedRoute
    }
  }
}

interface MatchRouteChildren {
  MatchResultRoute: typeof MatchResultRoute
}

const MatchRouteChildren: MatchRouteChildren = {
  MatchResultRoute: MatchResultRoute,
}

const MatchRouteWithChildren = MatchRoute._addFileChildren(MatchRouteChildren)

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  RoomsRoute: RoomsRouteWithChildren,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  PlayIndexRoute: PlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
